---

computername: Kerngehäuse
hostname: kerngehaeuse

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - jeromegamez/formulae
  - aws/tap

homebrew_apps:
  - 1password
  - alfred
  - bartender
  - brave-browser
  - cleanmymac
  - dash
  - discord
  - fantastical
  - fliqlo
  - font-fira-code
  - font-roboto
  - franz
  - gitup
  - gpg-suite
  - iina
  - iterm2
  - kaleidoscope
  - mailmate
  - osxfuse
  - paw
  - phpstorm
  - plug
  - sequel-pro
  - sonos
  - spillo
  - rescuetime
  - slack
  - spotify
  - sublime-merge
  - sublime-text
  - textual
  - the-unarchiver
  - tower
  - transmit
  - twitch

homebrew_packages:
  - aws-shell
  - awscli
  - aws-sam-cli
  - bash
  - chag
  - composer
  - curl
  - git
  - hub
  - httpie
  - imagemagick
  - jq
  - libmemcached
  - macvim
  - {name: make, install_options: "with-default-names" }
  - memcached
  - mysql@5.7
  - node
  - php
  - pkg-config
  - python
  - ruby
  - tree
  - wget
  - yadm
  - watch
  - zlib
  - zsh

mas_apps:
  - { name: 1Blocker, id: 1107421413 }
  - { name: Bear, id: 1091189122 }
  - { name: Carbonize, id: 1451177988 }
  - { name: Pages, id: 409201541 }
  - { name: Patterns, id: 429449079 }
  - { name: Pixelmator, id: 407963104 }
  - { name: Reeder, id: 880001334 }
  - { name: Tweetbot, id: 1384080005 }
