---

computername: Kerngehäuse
hostname: kerngehaeuse

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_use_fliqlo: yes
screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

change_shell_to_zsh: yes

yadm_repo_url: https://gitlab.com/jeromegamez/dotfiles.git

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_apps:
  - 1password
  - alfred
  - cleanmymac
  - dash
  - fantastical
  - fliqlo
  - font-fira-code
  - franz
  - gitup
  - gpg-suite
  - iterm2
  - kaleidoscope
  - mailmate
  - paw
  - phpstorm
  - plug
  - sequel-pro
  - sonos
  - rescuetime
  - slack
  - spotify
  - sublime-text
  - tower

homebrew_installed_packages:
  - curl
  - git
  - macvim
  - {name: make, install_options: "with-default-names" }
  - python
  - wget
  - yadm

mas_installed_apps:
  - { name: 1Blocker, id: 1107421413 }
  - { name: Patterns, id: 429449079 }
  - { name: Pixelmator, id: 407963104 }
  - { name: Reeder, id: 880001334 }
  - { name: Tweetbot, id: 1384080005 }
