---

- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - config.yml
        - default.config.yml
      tags: ['always']

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: mas
      tags: [mas]
    - role: settings
      tags: [settings]
    - role: zsh
      tags: [zsh]
      when: change_shell_to_zsh|bool == True
