---

- hosts: localhost
  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include user configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: [homebrew]
    - role: geerlingguy.mas
      tags: [mas]
    - role: settings
      tags: [settings]
    - role: zsh
      tags: [zsh]
      when: change_shell_to_zsh|bool == True
