---

- name: Save application states on quit ({{ save_application_state_on_quit }})
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: "{{ save_application_state_on_quit|bool }}"

- name: Expand save panel by default ({{ expand_save_panel_by_default }})
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "{{ expand_save_panel_by_default|bool }}"

- name: Expand print panel by default ({{ expand_print_panel_by_default }})
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: "{{ expand_print_panel_by_default|bool }}"

