---

- name: Install tools (homebrew).
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-compose
    - docker-credential-helper
    - docker-machine
    - docker-machine-driver-xhyve
