---

- name: "Determine hombrew's cask name for docker"
  set_fact:
    docker_cask_name: "{{ 'docker' if docker_version == 'stable' else ('docker-' + docker_version) }}"

- name: Tap caskroom/versions
  homebrew_tap:
    tap: caskroom/versions
  when: docker_cask_name != "docker"

- name: "Install {{ docker_cask_name }}"
  homebrew_cask:
    name: "{{ docker_cask_name }}"
