---

- name: Install tools (homebrew).
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - awscli
    - aws-shell
    - dnsmasq
    - docker-cloud
    - gitlab-ci-multi-runner
    - httpie
    - mariadb
    - terraform
    - terraform-inventory

- name: Install tools (npm global).
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - firebase-tools
    - gulp

- name: Install python libraries
  pip:
    name: "{{ item }}"
  with_items:
    - "passlib[bcrypt]"
    - Sphinx

- name: Install NGINX.
  homebrew:
    name: nginx
    state: latest
    install_options: with-gunzip,with-http2

- include: php.yml
  tags: [php]

- include: vagrant.yml
  tags: [vagrant]
