---

- name: Install PHP.
  homebrew:
    name: php
  ignore_errors: yes

- name: Install PHP extension dependencies
  homebrew:
    name: "{{ item }}"
  with_items: "{{ php_extension_dependencies }}"

- name: Install PHP extensions.
  pear:
    name: "{{ item }}"
  with_items: "{{ php_extensions }}"

- name: Install composer.
  homebrew:
    name: composer
    state: latest

- name: Install global composer packages.
  composer:
    command: require
    global_command: yes
    arguments: "{{ item }}"
  with_items: "{{ composer_global_packages }}"
  when: not ansible_check_mode
