---

- name: Install vagrant.
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - virtualbox
    - virtualbox-extension-pack
    - vagrant

- name: Get installed vagrant plugins.
  shell: vagrant plugin list
  register: vagrant_plugin_list
  changed_when: false
  check_mode: no

- name: Install vagrant plugins.
  shell: "vagrant plugin install {{ item }}"
  with_items:
    - vagrant-bindfs
    - vagrant-hostmanager
  when: "'{{ item }}' not in vagrant_plugin_list.stdout"
