---

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install curl.
  homebrew:
    name: curl
    state: latest
    install_options: with-libidn,with-nghttp2

# Not using "state: linked" because this would be executed every run
- name: Link brewed curl.
  shell: brew link --force curl
  args:
    creates: /usr/local/bin/curl

- name: Install gnu-sed
  homebrew:
    name: gnu-sed
    state: latest
    install_options: with-default-names

- name: Install git.
  homebrew:
    name: git
    state: latest
    install_options: with-brewed-curl,with-brewed-ssl

- name: Install vim.
  homebrew:
    name: vim
    state: latest
    install_options: with-override-system-vi

- name: Install other essential brews.
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - tree
    - watch
    - wget
    - yarn
